In [1]:
%matplotlib inline
import os
import sys
import matplotlib.pyplot as plt
import numpy as np

sys.path.append(os.path.join(os.getcwd(), '..'))

from aye.kalman_filter import *

In [2]:
kf = KalmanFilter()
kf.init(np.matrix('0;0;1;1'))

In [5]:
kf.predict(1)
print(kf.X)
print(kf.P)

[[ 3.        ]
 [ 3.        ]
 [ 1.33333333]
 [ 1.33333333]]
[[ 2.          0.          1.          0.        ]
 [ 0.          2.          0.          1.        ]
 [ 1.          0.          0.66666667  0.        ]
 [ 0.          1.          0.          0.66666667]]


In [6]:
kf.update(np.matrix('3.25;3.25'))
print(kf.X)
print(kf.P)

[[ 3.16666667]
 [ 3.16666667]
 [ 1.41666667]
 [ 1.41666667]]
[[ 0.66666667  0.          0.33333333  0.        ]
 [ 0.          0.66666667  0.          0.33333333]
 [ 0.33333333  0.          0.33333333  0.        ]
 [ 0.          0.33333333  0.          0.33333333]]


array([[ 0.5,  0. ],
       [ 0. ,  0.5]])